# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.runs/synth_1/E906_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.cache/wt [current_project]
set_property parent.project_path E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:genesys2:part0:1.1 [current_project]
set_property ip_output_repo e:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_define.h
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_define.h
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/sysmap/rtl/sysmap.h
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_cfig.h
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_cfig.h
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/tb/had_drv.h
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cpu/rtl/cpu_cfig.h
}
set_property file_type "Verilog Header" [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_define.h]
set_property is_global_include true [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_define.h]
set_property file_type "Verilog Header" [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_define.h]
set_property is_global_include true [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_define.h]
set_property file_type "Verilog Header" [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/sysmap/rtl/sysmap.h]
set_property is_global_include true [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/sysmap/rtl/sysmap.h]
set_property file_type "Verilog Header" [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_cfig.h]
set_property is_global_include true [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_cfig.h]
set_property file_type "Verilog Header" [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_cfig.h]
set_property is_global_include true [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_cfig.h]
set_property file_type "Verilog Header" [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/tb/had_drv.h]
set_property is_global_include true [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/tb/had_drv.h]
set_property file_type "Verilog Header" [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cpu/rtl/cpu_cfig.h]
set_property is_global_include true [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cpu/rtl/cpu_cfig.h]
read_verilog -library xil_defaultlib {
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/common/rtl/BUFGCE.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/ahb/ahb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/ahb/ahb_fifo.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/ahb/ahb_fifo_counter.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/ahb/ahb_fifo_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/apb/apb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/apb/apb_bridge.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/booth_code_25_bit.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/booth_code_33_bit.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/system/cpu_sub_system_ahb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/mem/dahb_mem_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/system/err_gen.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/system/fpga_clk_gen.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpga/rtl/fpga_ram.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/gpio/gpio.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/gpio/gpio_apbif.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/gpio/gpio_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/mem/iahb_mem_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/mem/mem_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/multiplier_33x33_partial.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cpu/rtl/openE906.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/biu/rtl/pa_ahbl_if.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/biu/rtl/pa_ahbl_if_fo.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/bmu/rtl/pa_bmu_bus_if.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/bmu/rtl/pa_bmu_dbus_if.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/bmu/rtl/pa_bmu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_arb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_arb_32to1_kernel.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_arb_kernel.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_busif.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_cpuif_2cycle.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_expand.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_ff1_onehot.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_kid.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_kid_dummy.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_sel.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clic/rtl/pa_clic_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clint/rtl/pa_clint_busif.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clint/rtl/pa_clint_regs.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clint/rtl/pa_clint_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clk/rtl/pa_clk_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/clk/rtl/pa_clkrst_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cpu/rtl/pa_core.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cpu/rtl/pa_core_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_ext_csr.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_ext_inst.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_float_csr.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_info_csr.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_iui.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_regs.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_special.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_srst.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cp0/rtl/pa_cp0_trap_csr.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/biu/rtl/pa_dahbl_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_dcache_data_array.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_dcache_dirty_array.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_dcache_tag_array.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_dcache_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_cdc.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_cdc_lvl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_cdc_pulse.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_dbginfo.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_m_iie_all.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_mcontrol_0.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_mcontrol_1.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_mcontrol_2.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_mcontrol_output_select.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_pcfifo.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/dtu/rtl/pa_dtu_trigger_module.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpga/rtl/pa_f_spsram_1024x32.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpga/rtl/pa_f_spsram_2048x32.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpga/rtl/pa_f_spsram_256x4.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpga/rtl/pa_f_spsram_256x40.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpga/rtl/pa_f_spsram_256x41.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpga/rtl/pa_f_spsram_512x16.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_fadd_lop_s1_s.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_fadd_nm_shift_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_fadd_shift_sub_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_fadd_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_falu_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_falu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_fcnvt_ftoi_s.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_fcnvt_itof_s.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_fcnvt_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_dp.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_ex1_special_judge.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_frac_add.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_frac_mult.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_frac_shift.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_lza_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_multiplier_24x24_partial.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_src2_shifter_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fmau/rtl/pa_fmau_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/falu/rtl/pa_fspu_single.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/pmu/rtl/pa_hpcp_cnt.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/pmu/rtl/pa_hpcp_event.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/pmu/rtl/pa_hpcp_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/biu/rtl/pa_iahbl_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_decd_dsp.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_decd_fp.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_decd_rv32c.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_decd_rv32fd.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_decd_rv32im.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_decd_rv32x.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_dp.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_fpr.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_gpr.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_hs.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_id_fp.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_reg.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_reg32.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_reg32_high.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_reg_sp.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_split.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/idu/rtl/pa_idu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_bht.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_bht_array.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_btb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_btb_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ibuf.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ibuf_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ibuf_pop_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_icache.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_icache_data_array.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_icache_tag_array.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_id_pred.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ifetch.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ipack.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ipack_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_pcgen.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_pre_decd.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ras.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_ras_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_ifu_vec.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/pa_iu_addr_gen.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/pa_iu_alu.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/pa_iu_bju.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/pa_iu_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/pa_iu_div.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/pa_iu_div_shift2_kernel.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/pa_iu_mul.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/iu/rtl/pa_iu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_ag.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_arb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_dahbif.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_dc.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_dtif.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_icc.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_lfb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_lm.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_ncb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_rdl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_stb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_stb_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_vb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_vb_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_lsu_wb_entry.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/pmp/rtl/pa_pmp_acc_arb.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/pmp/rtl/pa_pmp_comp_hit.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/pmp/rtl/pa_pmp_enc.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/pmp/rtl/pa_pmp_regs.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/pmp/rtl/pa_pmp_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/rst/rtl/pa_rst_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/rtu/rtl/pa_rtu_cbus.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/rtu/rtl/pa_rtu_int.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/rtu/rtl/pa_rtu_lockup.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/rtu/rtl/pa_rtu_rbus.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/rtu/rtl/pa_rtu_retire.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/rtu/rtl/pa_rtu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/biu/rtl/pa_sahbl_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_spsram_1024x32.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_spsram_2048x32.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_spsram_256x4.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/lsu/rtl/pa_spsram_256x40.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_spsram_256x41.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/ifu/rtl/pa_spsram_512x16.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/cpu/rtl/pa_sys_io.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/sysmap/rtl/pa_sysmap_access.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/sysmap/rtl/pa_sysmap_busif.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/sysmap/rtl/pa_sysmap_hit.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/sysmap/rtl/pa_sysmap_reg.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/sysmap/rtl/pa_sysmap_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tcipif/rtl/pa_tcipif_behavior_bus.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tcipif/rtl/pa_tcipif_dummy_bus.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tcipif/rtl/pa_tcipif_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/pmu/pmu.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/system/px_had_sync.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/smpu/smpu_comp_hit.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/smpu/smpu_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/system/soc.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/mem/soc_fpga_ram.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/system/sync.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/system/tap2_sm.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_apb_master.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dm.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dm_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dmi_pulse_sync.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_rst_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dmi_sync_dff.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_dmi_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_chain.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_idr.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_io.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/debug/tdt_dtm_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/common/tdt_gated_clk_cell.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/E906_RTL_FACTORY/gen_rtl/tdt/rtl/top/tdt_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/timer/timer.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/uart/uart.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/uart/uart_apb_reg.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/uart/uart_baud_gen.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/uart/uart_ctrl.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/uart/uart_receive.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/uart/uart_trans.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/wic/wic.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/wic/wic_awake_en_32.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/imports/opene906-main/smart_run/logical/wic/wic_top.v
  E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/new/E906_top.v
}
read_ip -quiet E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/constrs_1/imports/digilent-xdc-master/Genesys-2-Master.xdc
set_property used_in_implementation false [get_files E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/constrs_1/imports/digilent-xdc-master/Genesys-2-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/EDA/Ubuntu_share/vivado_files/E906_FPGA_1/E906_FPGA_1.srcs/utils_1/imports/synth_1/E906_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top E906_top -part xc7k325tffg900-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef E906_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file E906_top_utilization_synth.rpt -pb E906_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
